#!/usr/bin/env python3
"""Billing-mode guard for cross-sns-audience-flow-analyzer - fail-closed PreToolUse hook (generated by cckit).

Blocks any AI-initiated change that would switch the Claude billing mode away from the
default OAuth subscription path (CLAUDE_CODE_OAUTH_TOKEN) to pay-per-use API direct
(ANTHROPIC_API_KEY) or modify auth settings without explicit human approval.

Rationale (governance):
  - OAuth subscription = sticky monthly cost (Pro/Max plan).
  - API direct = pay-per-token; an unattended loop that accidentally switches can rack
    up unbounded charges within hours.
  - This guard is in the same family as main_push_guard / governance-self-modification
    block: it severs the self-reference loop where an AI can authorize its own cost
    escalation.

Scope (what is blocked):
  - Bash commands that export / setx / set $env: ANTHROPIC_API_KEY
  - Bash commands that run `claude config set` / `claude setup-token` (auth changes)
  - Edit/Write of `.env*` files inserting ANTHROPIC_API_KEY
  - Edit/Write of `~/.claude/settings.json` auth section
  - Edit/Write of `.github/workflows/claude*.yml` replacing oauth_token with anthropic_api_key

Out of scope (passes through):
  - Reading or printing existing API key env vars (debug)
  - Unrelated env exports (PATH, NODE_ENV, etc.)
  - Editing unrelated parts of settings.json or workflow files

Exit codes:
  - 0: passes through (no violation)
  - 2: blocks with educational stderr message

Every catch terminates control flow (coding standard).
"""

import json
import re
import sys

# Patterns for Bash commands changing billing mode.
# Anchored at command start to avoid quoted-string-literal false positives.
_CMD_HEAD = r"(?:^|[;&|\n])\s*(?:sudo\s+)?"
_BASH_BILLING_PATTERNS: tuple[str, ...] = (
    _CMD_HEAD + r"export\s+ANTHROPIC_API_KEY\b",                # POSIX
    _CMD_HEAD + r"setx\s+ANTHROPIC_API_KEY\b",                  # Windows cmd
    _CMD_HEAD + r"\$env:ANTHROPIC_API_KEY\s*=",                 # PowerShell
    _CMD_HEAD + r"ANTHROPIC_API_KEY\s*=",                       # inline assignment
    _CMD_HEAD + r"claude\s+config\s+set\s+",                    # claude config set ...
    _CMD_HEAD + r"claude\s+setup-token\b",                      # token re-issue (treat as governance)
)

# File content patterns that, when written/edited, switch billing mode.
_FILE_CONTENT_PATTERNS: tuple[str, ...] = (
    r"^\s*ANTHROPIC_API_KEY\s*=",                               # .env line
    r"anthropic_api_key:\s*\$\{\{\s*secrets\.ANTHROPIC_API_KEY", # GH Actions YAML swap
    r'"anthropic_api_key"\s*:',                                  # settings.json field
)

# File-path triggers (edit of these files alone warrants extra scrutiny when content matches).
_SENSITIVE_PATHS_RE = re.compile(
    r"(\.env(\.[\w-]+)?|\.claude/settings\.json|\.github/workflows/claude.*\.ya?ml)$",
    re.IGNORECASE,
)


def violations_for_bash(command: str) -> list[str]:
    """Detect billing-mode changes in Bash command strings."""
    hits: list[str] = []
    for pat in _BASH_BILLING_PATTERNS:
        if re.search(pat, command, re.MULTILINE | re.IGNORECASE):
            hits.append(f"billing-mode change in Bash: matches `{pat}`")
    return hits


def violations_for_edit(file_path: str, new_content: str) -> list[str]:
    """Detect billing-mode changes in file Edit/Write payloads."""
    if not _SENSITIVE_PATHS_RE.search(file_path):
        return []
    hits: list[str] = []
    for pat in _FILE_CONTENT_PATTERNS:
        if re.search(pat, new_content, re.MULTILINE | re.IGNORECASE):
            hits.append(f"billing-mode change in edit to `{file_path}`: matches `{pat}`")
    return hits


def _block(reason: str) -> None:
    print(
        "BLOCKED: billing-mode guard.\n"
        f"  reason: {reason}\n"
        "  policy: OAuth subscription (CLAUDE_CODE_OAUTH_TOKEN) is the default.\n"
        "          Switching to pay-per-use (ANTHROPIC_API_KEY) is governance.\n"
        "          A human must perform this change manually; AI is not authorized.\n"
        "  to override: a human edits the relevant file or env directly, off the AI session.",
        file=sys.stderr,
    )
    sys.exit(2)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (ValueError, json.JSONDecodeError):
        return 0  # malformed -> pass through (other gates will fire)

    tool_name = str(payload.get("tool_name", ""))
    tool_input = payload.get("tool_input", {}) or {}

    if tool_name == "Bash":
        command = str(tool_input.get("command", ""))
        for v in violations_for_bash(command):
            _block(v)
        return 0

    if tool_name in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
        file_path = str(tool_input.get("file_path", ""))
        # Edit / NotebookEdit use `new_string`; Write uses `content`; MultiEdit uses `edits[].new_string`.
        new_content = str(
            tool_input.get("content")
            or tool_input.get("new_string")
            or "".join(str(e.get("new_string", "")) for e in tool_input.get("edits", []) if isinstance(e, dict))
        )
        for v in violations_for_edit(file_path, new_content):
            _block(v)
        return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
