#!/usr/bin/env python3
"""Clear-after-failures advisory for cross-sns-audience-flow-analyzer - PostToolUse hook (generated by cckit).

Implements Anthropic's guidance: "after 2 consecutive failed corrections, /clear and
re-prompt produces better results than accumulated context". Pure advisory - never
blocks (exit 0); just nudges the operator/agent to reset context when corrections
start to compound.

State model (intentionally minimal, stdlib-only):
  - Counter file: `.claude/state/correction-counter.txt` (single integer).
  - Increment on PostToolUse when `tool_response` indicates an error AND the
    previous tool call also errored (i.e. *consecutive* failed corrections).
  - Reset to 0 on any successful tool call.
  - When the counter reaches 2, emit a single stderr advisory line. Exit code is
    always 0 - this hook MUST NOT block tool flow (Anthropic guidance is a hint,
    not a gate).

Error detection (best-effort, stdlib only):
  - `tool_response.error` truthy, OR
  - `tool_response.is_error` truthy, OR
  - `tool_response.status` == "error", OR
  - non-dict tool_response that is a string containing "error" (very conservative).
Anything else is treated as success. Malformed/empty stdin = no-op (exit 0).
"""

import json
import pathlib
import sys

_STATE_DIR = pathlib.Path(".claude/state")
_COUNTER_FILE = _STATE_DIR / "correction-counter.txt"
_THRESHOLD = 2
_ADVISORY = (
    "ADVISORY: 2 consecutive corrections failed. /clear and re-prompt produces "
    "better results than accumulated context (Anthropic best practices)."
)


def _read_counter() -> int:
    try:
        return int(_COUNTER_FILE.read_text(encoding="utf-8").strip() or "0")
    except (OSError, ValueError):
        return 0


def _write_counter(value: int) -> None:
    try:
        _STATE_DIR.mkdir(parents=True, exist_ok=True)
        _COUNTER_FILE.write_text(str(value), encoding="utf-8")
    except OSError:
        # Advisory hook must never block; silently ignore state-write failures.
        return


def _is_error(tool_response: object) -> bool:
    if isinstance(tool_response, dict):
        if tool_response.get("error"):
            return True
        if tool_response.get("is_error"):
            return True
        if str(tool_response.get("status", "")).lower() == "error":
            return True
        return False
    if isinstance(tool_response, str):
        return "error" in tool_response.lower()
    return False


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0
    if not isinstance(payload, dict):
        return 0

    errored = _is_error(payload.get("tool_response"))
    counter = _read_counter()

    if errored:
        counter += 1
        _write_counter(counter)
        if counter >= _THRESHOLD:
            print(_ADVISORY, file=sys.stderr)
    else:
        if counter != 0:
            _write_counter(0)

    return 0  # Advisory only - never block.


if __name__ == "__main__":
    sys.exit(main())
