#!/usr/bin/env python3
"""Completion gate for cross-sns-audience-flow-analyzer - fail-closed PreToolUse hook (generated by cckit).

Hard-blocks destructive Bash commands (a backup gate that complements notation variants of
permissions deny; does NOT do shell quote/syntax parsing = not complete; the primary defense
is settings.json deny). Out-of-scope or unparsable input passes through (return 0); a
violation blocks (sys.exit(2)). Every catch must terminate control flow (coding standard).

Known uncaught cases (within the backup gate's design scope; the primary deny defense
covers them. Aiming for exhaustiveness here trades off increased FPs from misfires on
quoted-string literals):
  - subshells `(rm -rf /)` / command substitution `` `rm -rf /` `` / `$(rm -rf /)`
  - wrappers / prefixes `/bin/rm -rf /` / `command rm -rf` / `xargs rm -rf` /
    `env`, `nice`, `exec`, `time rm -rf /`
  - env-var prefix `FOO=1 rm -rf /` / alias bypass `\rm -rf /`
  - directly after control syntax `if ...; then rm -rf /; fi`
"""

import json
import re
import sys

# Match only at command start (beginning-of-line / right after a connector) to avoid
# misfires on quoted-string literals (e.g. echo "rm -rf"). re.MULTILINE also covers
# newline-separated subsequent line starts (line injection bypass prevention).
# Leading \s* allows leading whitespace/tabs.
_CMD = r"(?:^|[;&|])\s*(?:sudo\s+)?"
_DESTRUCTIVE_PATTERNS: tuple[str, ...] = (
    _CMD + r"rm\s+(-\w*[rR]\w*[fF]|-\w*[fF]\w*[rR])\b",        # rm -rf/-fr/-Rf/-fR (combined flags)
    _CMD + r"rm\s[^|;&]*(-[rR]\b|--recursive\b)[^|;&]*(-[fF]\b|--force\b)",  # r->f (separated, long/short mixed)
    _CMD + r"rm\s[^|;&]*(-[fF]\b|--force\b)[^|;&]*(-[rR]\b|--recursive\b)",  # f->r (order independent)
    _CMD + r"git\s+push(\s[^|;&]*)?\s(--force|-f)\b",          # force push (includes --force-with-lease)
    _CMD + r"git\s+push\s[^|;&]*[\s:+](main|master)(\s|$)",    # push to default branches (incl. HEAD:main / +main)
    _CMD + r"git\s+reset\s+--hard(\s|$)",
    _CMD + r"git\s+clean\s+-\w*[fF]",
)


def violations(tool_name: str, command: str) -> list[str]:
    """Enumerate destructive-command violations (pure function, testable)."""
    if tool_name != "Bash":
        return []
    return [p for p in _DESTRUCTIVE_PATTERNS if re.search(p, command, re.MULTILINE)]


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0  # Unparsable = treat as out-of-scope and pass through
    if not isinstance(payload, dict):
        return 0
    tool = str(payload.get("tool_name", ""))
    tool_input = payload.get("tool_input")
    command = str(tool_input.get("command", "")) if isinstance(tool_input, dict) else ""
    found = violations(tool, command)
    if found:
        print(f"BLOCKED (destructive command): {command!r} matched {found}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
