#!/bin/bash
# Generated by cckit: PreToolUse hook that narrows test-run command output to "failing lines only".
# Command output accumulates across turns, so compressing it here saves tokens at zero context cost.
# jq --arg performs JSON escaping (won't break JSON even with commands containing quotes or newlines).
# Only rewrites simple "single-line" test invocations. Anything with compound commands (| ; &),
# command substitution ($( ) / backticks), redirections (< >), or newlines (multi-line commands) is
# passed through unchanged ({} = no change) — and is NOT granted the permissionDecision:allow
# auto-approval either (to avoid escalating `pytest $(arbitrary)` or a second-line `rm -rf` under
# an `allow`). If jq is missing, also pass through.
input=$(cat)
cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty' 2>/dev/null)

# Multi-line commands containing newlines are short-circuited (prevents the ERE `$` matching a
# line end and thereby allowing the second line).
case "$cmd" in *$'\n'*) echo "{}"; exit 0;; esac

# Allowed suffix is safe characters only (excludes | ; & $ ` < > ( ) ). Use single-quoted literal regex
# to prevent bash expansion.
safe_test_cmd='^(npm test|pytest|go test|cargo test)[^|;&$`<>()]*$'
if [[ "$cmd" =~ $safe_test_cmd ]]; then
  filtered="$cmd 2>&1 | grep -A 5 -E '(FAIL|ERROR|error:|panic)' | head -100"
  jq -cn --arg c "$filtered" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"allow",updatedInput:{command:$c}}}'
else
  echo "{}"
fi
