#!/usr/bin/env python3
"""Security guidance PreToolUse hook for cross-sns-audience-flow-analyzer (generated by cckit).

Reference: https://github.com/anthropics/claude-code/tree/main/plugins/security-guidance

Scans Edit/Write/Bash tool invocations against 9 dangerous patterns. Stdlib only.
Default exit 0 (advisory WARNING to stderr). If false == "true",
exit 1 to block. Out-of-scope / unparsable input passes through (exit 0).

Patterns (each catch terminates control flow per coding-style.md rule):
  1. command_injection    : subprocess(..., shell=True), os.system
  2. xss_sink             : innerHTML, dangerouslySetInnerHTML
  3. dynamic_code         : eval(...), exec(...), new Function(
  4. dangerous_html       : document.write(
  5. unsafe_deserialize   : pickle.load, yaml.unsafe_load, yaml.load (no Loader)
  6. shell_exec           : os.popen, subprocess.Popen(..., shell=True)
  7. sql_concat           : execute("..." + var) / f"SELECT ... {var}"
  8. path_traversal       : ".." in user-supplied path segments
  9. hardcoded_credential : AWS_SECRET / API_KEY / PASSWORD literal assignment
"""

import json
import re
import sys

_BLOCKING: bool = "false".strip().lower() == "true"

_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("command_injection", re.compile(r"\bsubprocess\.[A-Za-z_]+\([^)]*shell\s*=\s*True|\bos\.system\s*\(")),
    ("xss_sink", re.compile(r"\.innerHTML\s*=|dangerouslySetInnerHTML")),
    ("dynamic_code", re.compile(r"\beval\s*\(|\bexec\s*\(|new\s+Function\s*\(")),
    ("dangerous_html", re.compile(r"document\.write\s*\(")),
    ("unsafe_deserialize", re.compile(r"pickle\.load[s]?\s*\(|yaml\.unsafe_load\s*\(|yaml\.load\s*\([^)]*\)(?!.*Loader)")),
    ("shell_exec", re.compile(r"\bos\.popen\s*\(|subprocess\.Popen\s*\([^)]*shell\s*=\s*True")),
    ("sql_concat", re.compile(r"(?i)(?:execute|query)\s*\(\s*[\"'][^\"']*(?:SELECT|INSERT|UPDATE|DELETE)\b[^\"']*[\"']\s*\+|f[\"'][^\"']*(?:SELECT|INSERT|UPDATE|DELETE)\b[^\"']*\{")),
    ("path_traversal", re.compile(r"[\"'][^\"']*\.\.[\\/][^\"']*[\"']")),
    ("hardcoded_credential", re.compile(r"(?i)(?:AWS_SECRET[A-Z_]*|API[_-]?KEY|SECRET[_-]?KEY|PASSWORD|PASSWD|TOKEN)\s*[:=]\s*[\"'][^\"'\s$\{]{6,}[\"']")),
]


def _extract_text(tool_name: str, tool_input: dict) -> str:
    """Gather scannable text from tool input (Write/Edit/MultiEdit/Bash)."""
    parts: list[str] = []
    if tool_name == "Bash":
        parts.append(str(tool_input.get("command", "")))
    else:
        parts.append(str(tool_input.get("content", "")))
        parts.append(str(tool_input.get("new_string", "")))
        edits = tool_input.get("edits")
        if isinstance(edits, list):
            for edit in edits:
                if isinstance(edit, dict):
                    parts.append(str(edit.get("new_string", "")))
    return "\n".join(parts)


def _scan(text: str) -> list[tuple[str, str]]:
    """Return list of (pattern_name, matched_snippet) hits."""
    hits: list[tuple[str, str]] = []
    for name, pat in _PATTERNS:
        m = pat.search(text)
        if m:
            snippet = m.group(0)[:120]
            hits.append((name, snippet))
    return hits


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0
    if not isinstance(payload, dict):
        return 0
    tool_name = str(payload.get("tool_name", ""))
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return 0
    text = _extract_text(tool_name, tool_input)
    if not text:
        return 0
    hits = _scan(text)
    if not hits:
        return 0
    verb = "BLOCKED" if _BLOCKING else "WARNING"
    for name, snippet in hits:
        print(f"{verb} (security-guidance:{name}): {snippet}", file=sys.stderr)
    print(f"{verb} (security-guidance): {len(hits)} pattern(s) matched in {tool_name}.", file=sys.stderr)
    return 1 if _BLOCKING else 0


if __name__ == "__main__":
    sys.exit(main())
