#!/usr/bin/env python3
"""Family-aware single-model session guard for cross-sns-audience-flow-analyzer (generated by cckit).

Tracks the MAIN session model's family (haiku-* / sonnet-* / opus-*) and emits an
**advisory** stderr message when the active model switches family mid-session — instead
of fail-closed blocking. Mid-session model switches still invalidate Anthropic's prompt
cache (cache entries are keyed by exact model name per Anthropic docs), so the warning
is preserved; however, official patterns like `opusplan` (see
https://code.claude.com/docs/en/model-config) deliberately switch between Opus (plan)
and Sonnet (implementation) within one session, so a hard block would block the
recommended workflow. Hence: advisory (exit 0), not block (exit 1).

Behavior:
  - Reads current model from PreToolUse stdin JSON (`{"model": "..."}`) with
    `CLAUDE_MODEL` env var fallback.
  - First invocation per session: record model + family in
    `.claude/state/session-model.txt`, exit 0.
  - Subsequent invocation, same model: exit 0 silently.
  - Subsequent invocation, different model:
      * If new model belongs to the same family (e.g. sonnet-4-5 -> sonnet-4-6):
        advisory stderr warn, exit 0 (cache still cold; minor cost).
      * If family changes AND pair is opus+sonnet: stderr labels it
        "opusplan-style switch detected, advisory only", exit 0.
      * Otherwise (other family change): generic advisory, exit 0.
  - Unparsable / unresolvable model: pass through, exit 0 (backup gate).

State-file backward compatibility: old format = bare "<model>\n"; new format =
"<model>\n<family>\n". Both are accepted on read; rewriting always uses the new format.

Every catch terminates control flow (coding standard). Uses only the Python stdlib.
"""

import json
import os
import pathlib
import sys

_STATE_PATH = pathlib.Path(".claude/state/session-model.txt")
_KNOWN_FAMILIES = ("haiku", "sonnet", "opus")
_OPUSPLAN_PAIR = frozenset({"opus", "sonnet"})


def _resolve_model(payload: object) -> str:
    """Resolve current model from stdin payload, falling back to CLAUDE_MODEL env var."""
    if isinstance(payload, dict):
        model = payload.get("model")
        if isinstance(model, str) and model.strip():
            return model.strip()
    return os.environ.get("CLAUDE_MODEL", "").strip()


def _family_of(model: str) -> str:
    """Map a model name to its family prefix (haiku/sonnet/opus) or '' if unknown."""
    lowered = model.lower()
    for family in _KNOWN_FAMILIES:
        if family in lowered:
            return family
    return ""


def _read_recorded() -> tuple[str, str]:
    """Read recorded (model, family). Accepts both old (1 line) and new (2 line) formats."""
    try:
        raw = _STATE_PATH.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError):
        return ("", "")
    lines = [line.strip() for line in raw.splitlines() if line.strip()]
    if not lines:
        return ("", "")
    model = lines[0]
    family = lines[1] if len(lines) >= 2 else _family_of(model)
    return (model, family)


def _write_recorded(model: str, family: str) -> None:
    _STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    _STATE_PATH.write_text(f"{model}\n{family}\n", encoding="utf-8")


def _emit_advisory(recorded_model: str, recorded_family: str, current_model: str, current_family: str) -> None:
    same_family = (
        recorded_family
        and current_family
        and recorded_family == current_family
    )
    is_opusplan_pair = (
        recorded_family
        and current_family
        and {recorded_family, current_family} == _OPUSPLAN_PAIR
    )
    if same_family:
        label = "intra-family switch (cache invalidation expected, minor cost)"
    elif is_opusplan_pair:
        label = "opusplan-style switch detected, advisory only"
    else:
        label = "cross-family switch (prompt cache invalidated)"
    print(
        f"ADVISORY (single-model session guard): model changed mid-session "
        f"({recorded_model!r} [{recorded_family or '?'}] -> {current_model!r} "
        f"[{current_family or '?'}]). {label}. Anthropic prompt cache is keyed by exact "
        f"model name, so this forces a cold re-read of CLAUDE.md / rules / skills. "
        f"Not blocking (exit 0) - official patterns like 'opusplan' "
        f"(https://code.claude.com/docs/en/model-config) intentionally switch models "
        f"within a single session.",
        file=sys.stderr,
    )


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        payload = None
    current = _resolve_model(payload)
    if not current:
        return 0  # cannot resolve model -> pass through (backup gate)
    current_family = _family_of(current)
    recorded_model, recorded_family = _read_recorded()
    if not recorded_model:
        _write_recorded(current, current_family)
        return 0  # first-seen: record and pass
    if current == recorded_model:
        return 0  # exact match: no cache invalidation
    _emit_advisory(recorded_model, recorded_family, current, current_family)
    # Update recorded model so subsequent calls compare against the now-active one
    # (otherwise every tool call after a switch re-emits the same advisory).
    _write_recorded(current, current_family)
    return 0  # advisory only (downgraded from exit 1 - see module docstring)


if __name__ == "__main__":
    sys.exit(main())
