#!/usr/bin/env python3
"""Suppression guard for cross-sns-audience-flow-analyzer - fail-closed PreToolUse hook (generated by cckit).

Blocks Write/Edit that **writes lint/type suppression directives into code files**
(deterministically enforces the rule "fix the cause, suppression is absolutely
forbidden"; moves reliance from prose adherence to machine enforcement).
**The language is determined by file extension, and only that language's patterns
apply** (`_BY_EXT` routing structurally eliminates cross-language pattern FPs):
  - JS/TS: `@ts-ignore` / `@ts-nocheck` / `@ts-expect-error` / `eslint-disable` / `biome-ignore`
  - Python: `# noqa`, `# flake8/ruff: noqa` (whole file) / `# type: ignore` /
    `# pylint/mypy/pyright: ...` / `# pyre-*`
  - Rust: `#[allow(...)]` / `#[expect(...)]` / `#[cfg_attr(..,allow(..))]`
    Go: `//nolint` / `//lint:ignore` / `//revive:disable`
  - Java/Kotlin/Scala: `@SuppressWarnings` / `@Suppress` / `@file:Suppress` /
    `@SuppressLint` / `@SuppressFBWarnings` (call parentheses required), Scala `@nowarn`
  - C#: `#pragma warning disable` / `[SuppressMessage(..)]`
    Ruby: `# rubocop:disable` / `# rubocop:todo`
(Because the hook is a script execution, it does not enter the LLM context and adds
language coverage at **zero token cost**.)

Backup gate = not complete (known limits; complemented by human review / CI):
  - **FP**: Legitimate code that merely "mentions" a suppression directive in a
    string/docstring/comment is also blocked (no syntactic parsing = text match).
    Avoid via rename/rewording. Docs (.md/.txt/.rst) and tests are excluded, but
  - **FN/bypass**: Moving the suppression into a test file (test_*/*.spec etc.)
    escapes inspection (intentional FP trade-off).
Every catch must terminate control flow (rule). Out-of-scope / unparsable input
passes through (return 0); violations block (exit 2).
"""

import json
import pathlib
import re
import sys

# Extension -> that language's suppression pattern (per-language routing structurally
# eliminates cross-language FPs). Restrict the noqa prefix to real linter names to
# avoid prose misfires (e.g. `# TODO: noqa`). Each `\s*\(` requires call parentheses
# to avoid identifier collisions (e.g. `@Suppress.foo`).
_PYTHON: re.Pattern[str] = re.compile(
    r"#\s*(?:(?:flake8|ruff|pep8|pycodestyle):\s*)?noqa\b"
    r"|#\s*(?:type:\s*ignore|pylint:\s*disable|mypy:\s*ignore|pyright:\s*ignore|pyre-ignore|pyre-fixme)")
_JS_TS: re.Pattern[str] = re.compile(
    r"//\s*(?:@ts-ignore|@ts-nocheck|@ts-expect-error|eslint-disable|biome-ignore)|/\*\s*eslint-disable")
_RUST: re.Pattern[str] = re.compile(
    r"#!?\[\s*(?:allow|expect)\s*\(|cfg_attr\s*\([^)]*\b(?:allow|expect)\s*\(")
_GO: re.Pattern[str] = re.compile(r"//\s*(?:nolint|lint:ignore|revive:disable)")
_JVM: re.Pattern[str] = re.compile(
    r"@(?:file:)?(?:SuppressWarnings|Suppress|SuppressLint|SuppressFBWarnings)\s*\("
    r"|@nowarn\b")  # Java/Kotlin/Scala (Scala @nowarn can be bare, so no parentheses required)
_CSHARP: re.Pattern[str] = re.compile(r"#\s*pragma\s+warning\s+disable|SuppressMessage\s*\(")
_RUBY: re.Pattern[str] = re.compile(r"#\s*rubocop:(?:disable|todo)")
_BY_EXT: dict[str, re.Pattern[str]] = {
    ".py": _PYTHON, ".pyi": _PYTHON,
    ".js": _JS_TS, ".jsx": _JS_TS, ".ts": _JS_TS, ".tsx": _JS_TS, ".mjs": _JS_TS, ".cjs": _JS_TS,
    ".mts": _JS_TS, ".cts": _JS_TS, ".vue": _JS_TS, ".svelte": _JS_TS,
    ".rs": _RUST, ".go": _GO,
    ".java": _JVM, ".kt": _JVM, ".kts": _JVM, ".scala": _JVM,
    ".cs": _CSHARP, ".rb": _RUBY,
}


def _is_test_path(path: str) -> bool:
    name = pathlib.PurePosixPath(path.replace("\\", "/")).name
    return name.startswith("test_") or "_test." in name or ".test." in name or ".spec." in name


def _edited_text(tool_input: dict) -> str:
    """Aggregate the input text (added content) of Write/Edit/MultiEdit."""
    parts = [str(tool_input.get("content", "")), str(tool_input.get("new_string", ""))]
    for edit in tool_input.get("edits", []) if isinstance(tool_input.get("edits"), list) else []:
        if isinstance(edit, dict):
            parts.append(str(edit.get("new_string", "")))
    return "\n".join(parts)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0
    if not isinstance(payload, dict):
        return 0
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return 0
    path = str(tool_input.get("file_path", ""))
    pattern = _BY_EXT.get(pathlib.PurePosixPath(path.replace("\\", "/")).suffix)
    if pattern is None or _is_test_path(path):
        return 0  # Docs / non-code / unsupported languages / tests are out of scope (FP suppression)
    if pattern.search(_edited_text(tool_input)):  # Apply only that language's suppression pattern
        print(f"BLOCKED (suppression forbidden): {path} contains a lint/type suppression comment. Fix the cause (rule).",
              file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
